<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SeatRush.Identity.Contracts\SeatRush.Identity.Contracts.csproj" />
    <ProjectReference Include="..\SeatRush.Identity.Domain\SeatRush.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\SeatRush.Shared\SeatRush.Shared.csproj" />
  </ItemGroup>

</Project>
