<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SeatRush.Payments.Contracts\SeatRush.Payments.Contracts.csproj" />
    <ProjectReference Include="..\SeatRush.Payments.Domain\SeatRush.Payments.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\SeatRush.Shared\SeatRush.Shared.csproj" />
  </ItemGroup>

</Project>
