<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeatRush.Events.Contracts\SeatRush.Events.Contracts.csproj" />
    <ProjectReference Include="..\SeatRush.Events.Domain\SeatRush.Events.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\SeatRush.Shared\SeatRush.Shared.csproj" />
  </ItemGroup>

</Project>
